# Generated by Django 4.0.7 on 2024-06-24 09:31

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whitelabel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='number')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last updated')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EventFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30, verbose_name='Nombre Evento')),
                ('central_alarm', models.BooleanField(default=False, verbose_name='Alarma Central')),
                ('user_alarm', models.BooleanField(default=False, null=True, verbose_name='user notification')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('email_alarm', models.BooleanField(default=False, verbose_name='email notification')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='alarm color')),
                ('alarm_sound', models.BooleanField(verbose_name='alarm')),
                ('sound_priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, null=True, verbose_name='priority')),
                ('type_alarm_sound', models.CharField(blank=True, max_length=255, null=True, verbose_name='sound type')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whitelabel.company', verbose_name='company')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='event')),
                ('modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, null=True, verbose_name='check')),
                ('main_event', models.IntegerField(verbose_name='main event')),
                ('server_date', models.DateTimeField(verbose_name='server date')),
                ('signal_date', models.DateTimeField(auto_now_add=True, verbose_name='signal date')),
                ('odometer', models.FloatField(verbose_name='odometer')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('calculated_speed', models.PositiveSmallIntegerField(verbose_name='calculated speed')),
                ('angle', models.PositiveSmallIntegerField(verbose_name='angle')),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='probability')),
                ('real_prediction', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='real prediction')),
                ('real', models.BooleanField(default=False, null=True, verbose_name='real')),
                ('alarm_type', models.BooleanField(default=False, verbose_name='alarm type')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitelabel.company', verbose_name='company')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='realtime.device', verbose_name='device')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['server_date'],
            },
        ),
    ]
