# Generated by Django 4.0.7 on 2024-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventfeature_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfeature',
            name='alias',
            field=models.CharField(max_length=30, verbose_name='Nombre Evento'),
        ),
        migrations.AlterField(
            model_name='eventfeature',
            name='central_alarm',
            field=models.BooleanField(default=False, verbose_name='Alarma Central'),
        ),
        migrations.AlterField(
            model_name='eventfeature',
            name='type_alarm_sound',
            field=models.CharField(blank=True, choices=[('https://sadevnp.blob.core.windows.net/media/alarm_sounds/Alarm1.wav', 'Alarm1'), ('https://sadevnp.blob.core.windows.net/media/alarm_sounds/Alarm2.wav', 'Alarm2'), ('https://sadevnp.blob.core.windows.net/media/alarm_sounds/Alarm3.wav', 'Alarm3')], max_length=255, null=True, verbose_name='sound type'),
        ),
    ]
