# Generated by Django 4.0.7 on 2024-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventfeature_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeature',
            name='custom_alarm_sound',
            field=models.FileField(blank=True, null=True, upload_to='custom_sounds/', verbose_name='custom_alarm_sound'),
        ),
        migrations.AlterField(
            model_name='eventfeature',
            name='type_alarm_sound',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sound type'),
        ),
    ]
