# Generated by Django 4.0.7 on 2024-07-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
