# Generated by Django 4.0.7 on 2024-06-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whitelabel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_Analytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_workspace', models.CharField(max_length=50, verbose_name='ID Workspace')),
                ('id_report', models.CharField(max_length=30, verbose_name='id_report')),
                ('workspace', models.CharField(max_length=30, verbose_name='workspace')),
                ('report', models.CharField(max_length=30, verbose_name='report')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='create date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('is_report', models.BooleanField(default=False, verbose_name='is_report')),
            ],
            options={
                'db_table': 'PowerBI"."advanced_analytical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyScoreSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField(blank=True, default=0, verbose_name='minimum score')),
                ('max_score', models.FloatField(blank=True, default=0, verbose_name='maximum score')),
                ('cotoff_date', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=1, verbose_name='cutoff date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whitelabel.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_companyscoresetup', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_Companyscoresetup', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('personal_identification_number', models.PositiveBigIntegerField(verbose_name='personal ID')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='last name')),
                ('address', models.CharField(blank=True, default='', max_length=30, verbose_name='address')),
                ('phone_number', models.PositiveBigIntegerField(default='', verbose_name='movil number')),
                ('password', models.CharField(default='', max_length=10, null=True, verbose_name='password')),
                ('date_joined', models.DateField(verbose_name='date joined')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whitelabel.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_driver', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_driver', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(null=True, verbose_name='date joined')),
                ('date_leaving', models.DateTimeField(blank=True, null=True, verbose_name='date leaving')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_driver_analytic', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoints.driver', verbose_name='driver')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_driver_analytic', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realtime.vehicle', verbose_name='vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='item')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last updated')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_items', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ItemScoreSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_item_score', models.FloatField(blank=True, default=0, verbose_name='points score item')),
                ('maximum_infractions', models.IntegerField(blank=True, default=0, verbose_name='maximum infractions')),
                ('subtract_points', models.FloatField(blank=True, default=0, verbose_name='subtract points')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('company_score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoints.companyscoresetup', verbose_name='company score')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_itemsscoresetup', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkpoints.itemscore', verbose_name='item')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_itemsscoresetup', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
        ),
        migrations.CreateModel(
            name='FatigueControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avl_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realtime.avldata', verbose_name='AVLData')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoints.driveranalytic', verbose_name='Driver')),
                ('items_score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoints.itemscoresetup', verbose_name='Items_score')),
                ('vehicle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realtime.vehicle', verbose_name='Vehicle')),
            ],
        ),
    ]
