# Generated by Django 4.0.7 on 2024-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtrackiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'realtrackiot',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='X Position')),
                ('y', models.IntegerField(verbose_name='Y Position')),
                ('w', models.IntegerField(verbose_name='Width')),
                ('h', models.IntegerField(verbose_name='Height')),
                ('componentType', models.CharField(choices=[('InformationWidget', 'Information Widget')], max_length=50, verbose_name='Component Type')),
            ],
            options={
                'verbose_name_plural': 'Widgets',
            },
        ),
    ]
