# Generated by Django 4.0.7 on 2024-06-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whitelabel', '0001_initial'),
        ('realtime', '0001_initial'),
        ('authentication', '0001_initial'),
        ('auth', '0013_group_name_en_group_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies_to_monitor',
            field=models.ManyToManyField(blank=True, db_table='authentication_user_companies_to_monitor', related_name='companies_to_monitor', related_query_name='companies_to_monitor', to='whitelabel.company', verbose_name='companies to monitor'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whitelabel.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='user',
            name='group_vehicles',
            field=models.ManyToManyField(blank=True, db_table='authentication_user_group_vehicles', related_name='group_vehicles', related_query_name='group_vehicles', to='realtime.vehiclegroup', verbose_name='group vehicles'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_user', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='user',
            name='process_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whitelabel.process', verbose_name='process_type'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicles_to_monitor',
            field=models.ManyToManyField(blank=True, db_table='authentication_user_vehicles_to_monitor', related_name='vehicles_to_monitor', related_query_name='vehicles_to_monitor', to='realtime.vehicle', verbose_name='vehicles to monitor'),
        ),
    ]
