# Generated by Django 4.0.7 on 2024-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_types_assets_asset_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands_assets',
            name='brand_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='brands_assets',
            name='brand_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='brands_assets',
            name='brand_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='line_assets',
            name='line_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='line_assets',
            name='line_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='line_assets',
            name='line_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Line'),
        ),
    ]
